packaging_format = 2

id = "diacamma"
name = "Diacamma"

description.en = "Management application for volunteers (association, condominium)"
description.fr = "Application de gestion pour les bénévoles (association, copropriété)"

version = "23.12.15.15~ynh1"

maintainers = ["Laurent Gay"]

[upstream]
license = "GNU General Public License v3.0"
website = "https://www.diacamma.org"
demo = "https://asso.diacamma.org"
code = "https://github.com/Diacamma2"
admindoc = "https://asso.diacamma.org/Docs"

[integration]
yunohost = '>= 11.2'
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "path"
    default = "/diacamma"

    [install.init_main_permission]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # This won't be saved as setting and will instead be used to initialize the SSOwat permission
    type = "group"
    default = "visitors"

    [install.lct_appli]
    ask.en = "Application"
    help.en = "What application do you want to install?"
    ask.fr = "Application"
    help.fr = "Quelle application voulez-vous installer ?"
    type = "select"
    choices.asso = "Diacamma Asso"
    choices.syndic = "Diacamma Syndic"
    choices.standard = "Lucterios Standard"
    
    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr","en"]

    [install.archive]
    ask.en = "Archive to upload"
    ask.fr = "Archive à télécharger"
    type = "string"
    optional = true

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those
    # https://yunohost.org/packaging_apps_resources

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    [resources.permissions]
    main.url = "/"
    admin.url = "/"
    admin.show_tile = false
    admin.allowed = "admins"

    [resources.apt]
    packages = "libxml2-dev,libxslt-dev,libjpeg-dev,libfreetype6,libfreetype6-dev,zlib1g-dev,libpq-dev,python3-pip,python3-dev,python3-tk,python3-pil,python3-venv,build-essential,pkg-config,postgresql,jq"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting
    [resources.database]
    # This will automatically provision/deprovison a database and store the corresponding credentials in settings $db_user, $db_name, $db_pwd
    type = "postgresql"

