#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SUPERVISOR & SYSTEMD SERVICE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

supervisorctl stop ${app}
supervisorctl remove ${app}
ynh_safe_rm "/etc/supervisor/conf.d/${app}.conf"
supervisorctl reread

ynh_config_remove_nginx

ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
