#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SUPERVISOR & SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..."

supervisorctl stop ${app}
supervisorctl remove ${app}
ynh_secure_remove "/etc/supervisor/conf.d/${app}.conf"
supervisorctl reread

ynh_remove_nginx_config

ynh_remove_logrotate


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last