#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers


#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Restoring the app main directory..." --weight=1

ynh_restore_file --origin_path="$install_dir"

#=================================================
# RESTORE SUPERVISOR CONFIGURATIONS
#=================================================
ynh_script_progression --message="Restoring system configurations related to $app..." --weight=1

# This should be a symetric version of what happens in the install script

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore_file --origin_path="/etc/supervisor/conf.d/${app}.conf"

ynh_restore_file --origin_path="/etc/logrotate.d/$app"

#=================================================
# RESTORE THE MYSQL DATABASE
#=================================================

ynh_script_progression --message="Restoring the PostgreSQL database..." --weight=1

# Restore dump
ynh_psql_connect_as --user=$db_user --password=$db_pwd --database=$db_name < dbbackup.sql

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Refresh the app main directory..." --weight=1

pushd $install_dir
venv/bin/lucterios_admin.py check
venv/bin/lucterios_admin.py update
venv/bin/lucterios_admin.py refreshall
popd

refresh_collect

check_params

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression --message="Reloading NGINX web server and $app's service..." --weight=1

supervisorctl reread
supervisorctl add ${app}
sleep 2
supervisorctl restart ${app}

ynh_systemd_action --service_name=nginx --action=reload

sleep 2

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Restoration completed for $app" --last
